### ISSUE TITLE
Battles on cyberdyne.psim.us keep crashing

### ISSUE THREAD

**Issue by Acharvak** [dramamine/leftovers-again#11]
![Like this](https://user-images.githubusercontent.com/9745165/30519603-da063674-9b9a-11e7-8e39-3946fe1d9339.png)

I tried it on different days, but no luck. When I click "Join Battle", it says the battle already has two players. I can play on play.pokemonshowdown.com just fine though.

**Comment by dramamine** [comment]
Thanks for bringing this to my attention!
This was a problem with the server code I was running. Some code got out of sync (data/scripts.js) which was causing matches to crash. This should be fixed now.

**Comment by Acharvak** [comment]
The battles no longer crash, but I still can't battle any bot because they immediately leave after the battle starts without even making one turn. Am I doing something wrong or is it another problem with the server ? Tried randumb, la-stabby, oras-phoebe, xy-cynthia in gen7random and gen6random.

**Comment by dramamine** [comment]
Eesh, yeah.
Looks like updating the server introduced another problem. The server's sending an empty request ("|request|") before it sends the real request that starts matches. This was causing bots to crash out with a JSON parse error (trying to parse an empty string).

Fixed in this commit and restarted all the bots.
27e59563b1c590f9d6badfbd6538ac051b74fa15

**Comment by Acharvak** [comment]
Cool, everything seems to work now!
